[2025-05-28T09:03:58.540+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-28T09:03:58.628+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cost_efficient_etl_pipeline.run_etl_script scheduled__2025-05-27T00:00:00+00:00 [queued]>
[2025-05-28T09:03:58.656+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cost_efficient_etl_pipeline.run_etl_script scheduled__2025-05-27T00:00:00+00:00 [queued]>
[2025-05-28T09:03:58.658+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-28T09:03:58.704+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_etl_script> on 2025-05-27 00:00:00+00:00
[2025-05-28T09:03:58.737+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=180) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-28T09:03:58.739+0000] {standard_task_runner.py:63} INFO - Started process 188 to run task
[2025-05-28T09:03:58.739+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'cost_efficient_etl_pipeline', 'run_etl_script', 'scheduled__2025-05-27T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_dag.py', '--cfg-path', '/tmp/tmp5usqo949']
[2025-05-28T09:03:58.742+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask run_etl_script
[2025-05-28T09:03:58.774+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-28T09:03:58.864+0000] {task_command.py:426} INFO - Running <TaskInstance: cost_efficient_etl_pipeline.run_etl_script scheduled__2025-05-27T00:00:00+00:00 [running]> on host 3a13b70a3a87
[2025-05-28T09:03:59.065+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vaishnavi' AIRFLOW_CTX_DAG_ID='cost_efficient_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_etl_script' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-27T00:00:00+00:00'
[2025-05-28T09:03:59.068+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-28T09:04:03.326+0000] {main_etl.py:27} INFO - Starting ETL process...
[2025-05-28T09:04:03.336+0000] {main_etl.py:42} ERROR - ETL process failed: [Errno 2] No such file or directory: 'data/input/sample_data.csv'
Traceback (most recent call last):
  File "/opt/airflow/src/etl/main_etl.py", line 29, in run_etl
    df = pd.read_csv(input_file)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/input/sample_data.csv'
[2025-05-28T09:04:03.360+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-28T09:04:03.361+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-28T09:04:03.386+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=cost_efficient_etl_pipeline, task_id=run_etl_script, run_id=scheduled__2025-05-27T00:00:00+00:00, execution_date=20250527T000000, start_date=20250528T090358, end_date=20250528T090403
[2025-05-28T09:04:03.446+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-28T09:04:03.476+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-28T09:04:03.481+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
